// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6kk3yLdsTiKB6yaqrzk5QJtuCFPhRukI',
    appId: '1:219305476482:web:a37a0f855738a218b74f9b',
    messagingSenderId: '219305476482',
    projectId: 'ecommerce-app-dd4fa',
    authDomain: 'ecommerce-app-dd4fa.firebaseapp.com',
    storageBucket: 'ecommerce-app-dd4fa.appspot.com',
    measurementId: 'G-2LJKR78NQL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDOw9TsAtpYIvSfF8XPnxZR4YDbhgRqdk',
    appId: '1:219305476482:android:56e50be0461a3c62b74f9b',
    messagingSenderId: '219305476482',
    projectId: 'ecommerce-app-dd4fa',
    storageBucket: 'ecommerce-app-dd4fa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzTfbtMHC0Y1IUwkhd9-9fsKI9J37504k',
    appId: '1:219305476482:ios:9dc7f9520516bd20b74f9b',
    messagingSenderId: '219305476482',
    projectId: 'ecommerce-app-dd4fa',
    storageBucket: 'ecommerce-app-dd4fa.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzTfbtMHC0Y1IUwkhd9-9fsKI9J37504k',
    appId: '1:219305476482:ios:7e282bfb7f9f5db9b74f9b',
    messagingSenderId: '219305476482',
    projectId: 'ecommerce-app-dd4fa',
    storageBucket: 'ecommerce-app-dd4fa.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
